services:
  - type: web
    name: webova-aplikacia-kniznica
    env: python
    plan: free
    rootDir: library_project
    buildCommand: ./build.sh
    startCommand: gunicorn library_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
